FROM node:alpine

WORKDIR /opt/2020ciot-wma

COPY . .

RUN npm install -g nodemon
RUN rm -f docker-compose.yml && rm -f Dockerfile && npm i

ENTRYPOINT [ "nodemon", "--inspect", "./bin/www" ]
