import { useEffect, useState } from "react"

export default function ActiveNotifications() {
  const [alerts, setAlerts] = useState();

  useEffect(() => {
    if (alerts) {
      return;
    }

    const fleetStatus = JSON.parse(sessionStorage.getItem('fleetStatus'));
    const thingName = encodeURI(fleetStatus.wlgw.thingName);

    fetch(`/api/alerts?wlGWThingName=${thingName}`)
      .then(response => {
        if (response.status === 200) {
          response.json().then(alerts => {
            alerts.forEach(alert => {
              const fromDate = new Date(alert.data.fromTimestamp);
              const toDate = new Date(alert.data.toTimestamp);

              const fromHours = fromDate.getHours();
              const fromMinutes = fromDate.getMinutes();
              const fromAm = (fromHours > 12 ? ' pm' : ' am');

              const toHours = toDate.getHours();
              const toMinutes = toDate.getMinutes();
              const toAm = (toHours > 12 ? ' pm' : ' am');

              alert.data.timeRange = `${fromHours}:${fromMinutes} ${fromAm} to ${toHours}:${toMinutes} ${toAm}`;
            });
            setAlerts(alerts);
          });
        }
      });

  }, [alerts]);

  return (
    <div>
      <h3>Active notifications</h3>
      <p className='fw-normal'>This page shows recent alerts generated by the water management system.</p>
      {!alerts &&
        <div className='d-flex justify-content-center'>
            <div className='spinner-border m-5' role='status' style={{ width: '3rem', height: '3rem' }}></div>
        </div>}
      {alerts &&
        <div className="row">
          <div className="col-8">
            <div className='card mb-3 top-m-5'>
              <div className='row g-0 h-100'>
                <div className='col-md-4 bg-warning'>
                  <div className='img-fluid rounded-start d-flex align-items-center justify-content-center'>
                    <i className='bi bi-droplet-half' style={{ fontSize: '07rem', color: 'red' }}></i>
                  </div>
                </div>
                <div className='col-md-8'>
                  <div className='card-body'>
                    <h5 className='card-title'>Water flowed continuously!</h5>
                    <p className='card-text'>
                      Continuous water flow was observed. Water was continuously at the rate of <span className='fw-bold'>{alerts[0].data.mean} ltr</span> per minute between 
                      &nbsp;<span className='fw-bold'>{alerts[0].data.timeRange}</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  )
}